"""
Tenancy Contract Model

The registered tenancy contract generated by a rental officer from an
accepted application (plans/valuadis-rentals/plan.mdx, Phase C). The
contract number is a per-year registry sequence (AA-RNT-<year>-<seq>) that
appears on paper, in tax records, and in disputes — it must be stable,
unique, human-quotable, and never reused. A contract activates only when a
matching deposit receipt is recorded; money is evidenced, never held (no
custody in v1).
"""

import enum

from sqlalchemy import (
    CheckConstraint,
    Column,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    UniqueConstraint,
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.core.database import Base


class TenancyContractStatus(str, enum.Enum):
    """Tenancy contract status enumeration."""

    DRAFT = "draft"
    ACTIVE = "active"
    TERMINATED = "terminated"
    EXPIRED = "expired"


class TenancyContract(Base):
    __tablename__ = "tenancy_contracts"

    id = Column(Integer, primary_key=True, index=True)

    # Registry contract number: AA-RNT-<year>-<zero-padded-seq>. Allocated
    # server-side from a per-year sequence (rental_contract_sequences) under
    # a row lock, with this unique constraint as the hard backstop.
    contract_no = Column(String(30), unique=True, nullable=False, index=True)

    listing_id = Column(
        Integer, ForeignKey("rental_listings.id", ondelete="CASCADE"), nullable=False, index=True
    )
    # One accepted application yields at most one contract.
    application_id = Column(
        Integer,
        ForeignKey("rental_applications.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
    )

    # Captured from the accepted offer at creation; not client-trusted.
    monthly_rent = Column(Float, nullable=False)
    start_date = Column(Date, nullable=False)
    end_date = Column(Date, nullable=False)

    # First + last month by default (2 x monthly_rent); an officer may edit
    # with an audited reason before a receipt is recorded.
    deposit_amount = Column(Float, nullable=False)
    deposit_receipt_ref = Column(String(120), nullable=True)
    deposit_paid_on = Column(Date, nullable=True)
    deposit_recorded_at = Column(DateTime(timezone=True), nullable=True)

    status = Column(String(20), default=TenancyContractStatus.DRAFT.value, nullable=False, index=True)
    activated_at = Column(DateTime(timezone=True), nullable=True)
    contract_pdf = Column(String(500), nullable=True)

    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False
    )

    listing = relationship("RentalListing")
    application = relationship("RentalApplication")

    __table_args__ = (
        UniqueConstraint("contract_no", name="uq_tenancy_contracts_contract_no"),
        CheckConstraint(
            "status IN ('draft','active','terminated','expired')",
            name="ck_tenancy_contracts_status",
        ),
        CheckConstraint("deposit_amount > 0", name="ck_tenancy_contracts_deposit_positive"),
        CheckConstraint("end_date > start_date", name="ck_tenancy_contracts_dates"),
    )

    def __repr__(self):
        return (
            f"<TenancyContract(id={self.id}, contract_no={self.contract_no}, "
            f"status={self.status})>"
        )


class RentalContractSequence(Base):
    """Per-year allocation counter for contract numbers.

    A dedicated table (rather than a native DB sequence) keeps allocation
    per-year and portable across Postgres (prod) and SQLite (tests). The row
    for a year is locked (SELECT ... FOR UPDATE on Postgres; SQLite
    serializes writes) while its counter is incremented, so concurrent
    contract creation cannot collide on a number.
    """

    __tablename__ = "rental_contract_sequences"

    year = Column(Integer, primary_key=True)
    last_value = Column(Integer, nullable=False, default=0, server_default="0")

    def __repr__(self):
        return f"<RentalContractSequence(year={self.year}, last_value={self.last_value})>"
