"""Centralized scraper-related service limits used by schemas, endpoints, and tests."""

SCRAPER_LIST_DEFAULT_LIMIT = 100
SCRAPER_LIST_MAX_LIMIT = 200
SCRAPER_LOG_DEFAULT_LIMIT = 50
SCRAPER_LOG_MAX_LIMIT = 200

SCRAPER_CREATE_MAX_PAGES = 100
SCRAPER_CREATE_DEFAULT_PAGES = 50

SCRAPER_RUN_SCHEMA_MAX_PAGES = 100
SCRAPER_RUN_SCHEMA_MAX_TARGET_ITEMS = 1000
SCRAPER_RUN_MAX_PAGES = 50
SCRAPER_RUN_MAX_TARGET_ITEMS = 200

SCRAPER_TEST_NAVIGATION_TIMEOUT_MS = 12000
SCRAPER_TEST_SELECTOR_WAIT_MS = 250
SCRAPER_TEST_SAMPLE_LIMIT = 3
